# Generated by Django 4.0.4 on 2022-06-15 09:55

import django.contrib.gis.geos.point
from django.db import migrations
import location_field.models.spatial


class Migration(migrations.Migration):

    dependencies = [
        ('markers', '0002_alter_battle_location_alter_fort_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battle',
            name='location',
            field=location_field.models.spatial.LocationField(default=django.contrib.gis.geos.point.Point(55.9678, 54.7431), srid=4326),
        ),
        migrations.AlterField(
            model_name='fort',
            name='location',
            field=location_field.models.spatial.LocationField(default=django.contrib.gis.geos.point.Point(55.9678, 54.7431), srid=4326),
        ),
        migrations.AlterField(
            model_name='monument',
            name='location',
            field=location_field.models.spatial.LocationField(default=django.contrib.gis.geos.point.Point(55.9678, 54.7431), srid=4326),
        ),
        migrations.AlterField(
            model_name='regiment',
            name='location',
            field=location_field.models.spatial.LocationField(default=django.contrib.gis.geos.point.Point(55.9678, 54.7431), srid=4326),
        ),
        migrations.AlterField(
            model_name='toponym',
            name='location',
            field=location_field.models.spatial.LocationField(default=django.contrib.gis.geos.point.Point(55.9678, 54.7431), srid=4326),
        ),
    ]
