# Generated by Django 4.0.4 on 2022-06-15 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markers', '0003_alter_battle_location_alter_fort_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fort',
            name='amenity1',
            field=models.CharField(default='fort', editable=False, max_length=255),
        ),
        migrations.AlterField(
            model_name='fort',
            name='amenity',
            field=models.CharField(default='Крепость', editable=False, max_length=255),
        ),
    ]
