# Generated by Django 4.0.4 on 2022-06-15 11:00

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('markers', '0005_route_kuda_route_otkuda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='location',
            field=django.contrib.gis.db.models.fields.LineStringField(null=True, srid=4326),
        ),
    ]
