# Generated by Django 4.0.4 on 2022-06-15 11:14

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markers', '0007_alter_route_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mesh1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', django.contrib.gis.db.models.fields.MultiLineStringField(null=True, srid=4326)),
                ('polk', models.CharField(max_length=255)),
                ('otkuda', models.CharField(blank=True, max_length=255, null=True)),
                ('kuda', models.CharField(blank=True, max_length=255, null=True)),
                ('duration', models.CharField(blank=True, max_length=255, null=True)),
                ('length', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mesh2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', django.contrib.gis.db.models.fields.MultiLineStringField(null=True, srid=4326)),
                ('polk', models.CharField(max_length=255)),
                ('otkuda', models.CharField(blank=True, max_length=255, null=True)),
                ('kuda', models.CharField(blank=True, max_length=255, null=True)),
                ('duration', models.CharField(blank=True, max_length=255, null=True)),
                ('length', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Polk1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', django.contrib.gis.db.models.fields.MultiLineStringField(null=True, srid=4326)),
                ('polk', models.CharField(max_length=255)),
                ('otkuda', models.CharField(blank=True, max_length=255, null=True)),
                ('kuda', models.CharField(blank=True, max_length=255, null=True)),
                ('duration', models.CharField(blank=True, max_length=255, null=True)),
                ('length', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Polk10',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', django.contrib.gis.db.models.fields.MultiLineStringField(null=True, srid=4326)),
                ('polk', models.CharField(max_length=255)),
                ('otkuda', models.CharField(blank=True, max_length=255, null=True)),
                ('kuda', models.CharField(blank=True, max_length=255, null=True)),
                ('duration', models.CharField(blank=True, max_length=255, null=True)),
                ('length', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Polk11',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', django.contrib.gis.db.models.fields.MultiLineStringField(null=True, srid=4326)),
                ('polk', models.CharField(max_length=255)),
                ('otkuda', models.CharField(blank=True, max_length=255, null=True)),
                ('kuda', models.CharField(blank=True, max_length=255, null=True)),
                ('duration', models.CharField(blank=True, max_length=255, null=True)),
                ('length', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Polk12',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', django.contrib.gis.db.models.fields.MultiLineStringField(null=True, srid=4326)),
                ('polk', models.CharField(max_length=255)),
                ('otkuda', models.CharField(blank=True, max_length=255, null=True)),
                ('kuda', models.CharField(blank=True, max_length=255, null=True)),
                ('duration', models.CharField(blank=True, max_length=255, null=True)),
                ('length', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Polk13',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', django.contrib.gis.db.models.fields.MultiLineStringField(null=True, srid=4326)),
                ('polk', models.CharField(max_length=255)),
                ('otkuda', models.CharField(blank=True, max_length=255, null=True)),
                ('kuda', models.CharField(blank=True, max_length=255, null=True)),
                ('duration', models.CharField(blank=True, max_length=255, null=True)),
                ('length', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Polk14',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', django.contrib.gis.db.models.fields.MultiLineStringField(null=True, srid=4326)),
                ('polk', models.CharField(max_length=255)),
                ('otkuda', models.CharField(blank=True, max_length=255, null=True)),
                ('kuda', models.CharField(blank=True, max_length=255, null=True)),
                ('duration', models.CharField(blank=True, max_length=255, null=True)),
                ('length', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Polk15',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', django.contrib.gis.db.models.fields.MultiLineStringField(null=True, srid=4326)),
                ('polk', models.CharField(max_length=255)),
                ('otkuda', models.CharField(blank=True, max_length=255, null=True)),
                ('kuda', models.CharField(blank=True, max_length=255, null=True)),
                ('duration', models.CharField(blank=True, max_length=255, null=True)),
                ('length', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Polk16',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', django.contrib.gis.db.models.fields.MultiLineStringField(null=True, srid=4326)),
                ('polk', models.CharField(max_length=255)),
                ('otkuda', models.CharField(blank=True, max_length=255, null=True)),
                ('kuda', models.CharField(blank=True, max_length=255, null=True)),
                ('duration', models.CharField(blank=True, max_length=255, null=True)),
                ('length', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Polk17',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', django.contrib.gis.db.models.fields.MultiLineStringField(null=True, srid=4326)),
                ('polk', models.CharField(max_length=255)),
                ('otkuda', models.CharField(blank=True, max_length=255, null=True)),
                ('kuda', models.CharField(blank=True, max_length=255, null=True)),
                ('duration', models.CharField(blank=True, max_length=255, null=True)),
                ('length', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Polk18',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', django.contrib.gis.db.models.fields.MultiLineStringField(null=True, srid=4326)),
                ('polk', models.CharField(max_length=255)),
                ('otkuda', models.CharField(blank=True, max_length=255, null=True)),
                ('kuda', models.CharField(blank=True, max_length=255, null=True)),
                ('duration', models.CharField(blank=True, max_length=255, null=True)),
                ('length', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Polk19',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', django.contrib.gis.db.models.fields.MultiLineStringField(null=True, srid=4326)),
                ('polk', models.CharField(max_length=255)),
                ('otkuda', models.CharField(blank=True, max_length=255, null=True)),
                ('kuda', models.CharField(blank=True, max_length=255, null=True)),
                ('duration', models.CharField(blank=True, max_length=255, null=True)),
                ('length', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Polk2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', django.contrib.gis.db.models.fields.MultiLineStringField(null=True, srid=4326)),
                ('polk', models.CharField(max_length=255)),
                ('otkuda', models.CharField(blank=True, max_length=255, null=True)),
                ('kuda', models.CharField(blank=True, max_length=255, null=True)),
                ('duration', models.CharField(blank=True, max_length=255, null=True)),
                ('length', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Polk20',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', django.contrib.gis.db.models.fields.MultiLineStringField(null=True, srid=4326)),
                ('polk', models.CharField(max_length=255)),
                ('otkuda', models.CharField(blank=True, max_length=255, null=True)),
                ('kuda', models.CharField(blank=True, max_length=255, null=True)),
                ('duration', models.CharField(blank=True, max_length=255, null=True)),
                ('length', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Polk3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', django.contrib.gis.db.models.fields.MultiLineStringField(null=True, srid=4326)),
                ('polk', models.CharField(max_length=255)),
                ('otkuda', models.CharField(blank=True, max_length=255, null=True)),
                ('kuda', models.CharField(blank=True, max_length=255, null=True)),
                ('duration', models.CharField(blank=True, max_length=255, null=True)),
                ('length', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Polk4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', django.contrib.gis.db.models.fields.MultiLineStringField(null=True, srid=4326)),
                ('polk', models.CharField(max_length=255)),
                ('otkuda', models.CharField(blank=True, max_length=255, null=True)),
                ('kuda', models.CharField(blank=True, max_length=255, null=True)),
                ('duration', models.CharField(blank=True, max_length=255, null=True)),
                ('length', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Polk5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', django.contrib.gis.db.models.fields.MultiLineStringField(null=True, srid=4326)),
                ('polk', models.CharField(max_length=255)),
                ('otkuda', models.CharField(blank=True, max_length=255, null=True)),
                ('kuda', models.CharField(blank=True, max_length=255, null=True)),
                ('duration', models.CharField(blank=True, max_length=255, null=True)),
                ('length', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Polk6',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', django.contrib.gis.db.models.fields.MultiLineStringField(null=True, srid=4326)),
                ('polk', models.CharField(max_length=255)),
                ('otkuda', models.CharField(blank=True, max_length=255, null=True)),
                ('kuda', models.CharField(blank=True, max_length=255, null=True)),
                ('duration', models.CharField(blank=True, max_length=255, null=True)),
                ('length', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Polk7',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', django.contrib.gis.db.models.fields.MultiLineStringField(null=True, srid=4326)),
                ('polk', models.CharField(max_length=255)),
                ('otkuda', models.CharField(blank=True, max_length=255, null=True)),
                ('kuda', models.CharField(blank=True, max_length=255, null=True)),
                ('duration', models.CharField(blank=True, max_length=255, null=True)),
                ('length', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Polk8',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', django.contrib.gis.db.models.fields.MultiLineStringField(null=True, srid=4326)),
                ('polk', models.CharField(max_length=255)),
                ('otkuda', models.CharField(blank=True, max_length=255, null=True)),
                ('kuda', models.CharField(blank=True, max_length=255, null=True)),
                ('duration', models.CharField(blank=True, max_length=255, null=True)),
                ('length', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Polk9',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', django.contrib.gis.db.models.fields.MultiLineStringField(null=True, srid=4326)),
                ('polk', models.CharField(max_length=255)),
                ('otkuda', models.CharField(blank=True, max_length=255, null=True)),
                ('kuda', models.CharField(blank=True, max_length=255, null=True)),
                ('duration', models.CharField(blank=True, max_length=255, null=True)),
                ('length', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
