# Generated by Django 4.0.4 on 2022-06-15 11:38

import django.contrib.gis.geos.point
from django.db import migrations, models
import location_field.models.spatial


class Migration(migrations.Migration):

    dependencies = [
        ('markers', '0008_mesh1_mesh2_polk1_polk10_polk11_polk12_polk13_polk14_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', location_field.models.spatial.LocationField(default=django.contrib.gis.geos.point.Point(55.9678, 54.7431), srid=4326)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
    ]
