# Generated by Django 4.0.4 on 2022-06-15 11:51

import django.contrib.gis.geos.point
from django.db import migrations, models
import location_field.models.spatial


class Migration(migrations.Migration):

    dependencies = [
        ('markers', '0009_cities'),
    ]

    operations = [
        migrations.CreateModel(
            name='Uezd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', location_field.models.spatial.LocationField(default=django.contrib.gis.geos.point.Point(55.9678, 54.7431), srid=4326)),
                ('description', models.TextField(blank=True, max_length=2000, null=True)),
                ('audio', models.CharField(blank=True, default='', max_length=255)),
                ('photo', models.CharField(blank=True, default='', max_length=255)),
                ('video', models.CharField(blank=True, default='', max_length=255)),
                ('amenity', models.CharField(default='Уезд', editable=False, max_length=255)),
                ('amenity1', models.CharField(default='uezd', editable=False, max_length=255)),
            ],
        ),
    ]
