# Generated by Django 4.0.4 on 2022-06-15 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markers', '0010_uezd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monument',
            name='year',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
