# Generated by Django 4.0.4 on 2022-06-15 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markers', '0011_alter_monument_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regiment',
            name='commander',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
