# Generated by Django 4.0.4 on 2022-06-15 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markers', '0012_alter_regiment_commander'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regiment',
            name='size',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
