# Generated by Django 4.0.4 on 2022-06-15 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markers', '0013_alter_regiment_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regiment',
            name='period',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
