# Generated by Django 4.0.4 on 2022-06-15 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markers', '0014_alter_regiment_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='cities',
            name='amenity',
            field=models.CharField(default='Город', editable=False, max_length=255),
        ),
        migrations.AddField(
            model_name='cities',
            name='amenity1',
            field=models.CharField(default='cities', editable=False, max_length=255),
        ),
    ]
