# Generated by Django 4.0.4 on 2022-06-25 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markers', '0015_cities_amenity_cities_amenity1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linetoponym',
            name='amenity',
            field=models.CharField(default='Монумент', editable=False, max_length=255),
        ),
        migrations.AlterField(
            model_name='toponym',
            name='amenity',
            field=models.CharField(default='Монумент', editable=False, max_length=255),
        ),
    ]
